name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Build
        run: docker build --target build -t testme .
      -
        name: Test
        run: docker run --rm testme npm test
